### PR TITLE
docs: remove outdated instruction

### PR DESCRIPTION
**Pull request by raszi**

### CODE REVIEW

**Comment by solbu** [comment]
I am the Mageia packager for this software in Mageia.
The instructions you removed _Are_ the official instructions on how to install any package, which includes _this_ package.

**Comment by raszi** [comment]
Well, in that case, the screenshots are incorrect and show a different app [here](https://madb.mageialinux-online.org/show?distribution=cauldron&architecture=x86_64&rpm=colorize&repo=&group=&page=).

**Comment by raszi** [comment]
And also the URL is pointing to your fork which is behind the main branch.

**Comment by solbu** [comment]
All madb package screenshots are linked from the debian screenshots page.
Debian has a package that is _also_ called colorize, which is a completely different program.
We had the same problem with the CD ripper «grip». I'll notify the maintainers of the database to add this program to the screenshot exclusion list.

We use my fork simply because we needed a tagged release that included the Makefile.

**Comment by raszi** [comment]
I see, I can tag the release and put back the instructions.

**Comment by solbu** [comment]
Then we can fix the links in mageia, going forward. :-)

**Pull request merged**
